/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import GUI.Dialog.NewCommitteeDialog;
import javax.swing.*;
import BackEnd.ManagerSystem.EventManager;
import BackEnd.EventSystem.Committee;
import BackEnd.ManagerSystem.MainManager;
import BackEnd.UserSystem.User;
/**
 *
 * @author Sid
 */
public class CommitteeListPanel extends javax.swing.JPanel {

    /**
     * Creates new form CommitteeListPanel
     */
    private MainManager manager;
    private CommitteePanel committeePanel;
    public CommitteeListPanel() {
        initComponents();
        manager = MainManager.getInstance();
        committeePanel = new CommitteePanel();
        committeePanelHolder.add(committeePanel);
        updateInfo();
        if(committeeList.getModel().getSize() ==0)
        {
            committeePanel.setVisible(false);
        }
        else
        {
            committeeList.setSelectedIndex(0);
        }
    }
    
    public void updateInfo()
    {
        DefaultListModel model = new DefaultListModel();
        model.clear();
        for(Committee c : manager.getEventManager().getSelectedEvent().getCommitteeList()){
            model.addElement(c.getTitle());
        }
        committeeList.setModel(model);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        noPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        committeeListScrollPane = new javax.swing.JScrollPane();
        committeeList = new javax.swing.JList();
        committeeListLabel = new javax.swing.JLabel();
        addCommitteeButton = new javax.swing.JButton();
        removeCommitteeButton = new javax.swing.JButton();
        committeePanelHolder = new javax.swing.JPanel();

        noPanel.setBackground(java.awt.SystemColor.activeCaption);

        jLabel1.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("No committees Created Yet");
        noPanel.add(jLabel1);

        setPreferredSize(new java.awt.Dimension(750, 600));

        committeeList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        committeeList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                committeeListValueChanged(evt);
            }
        });
        committeeListScrollPane.setViewportView(committeeList);

        committeeListLabel.setText("Committee List");

        addCommitteeButton.setText("+");
        addCommitteeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCommitteeButtonActionPerformed(evt);
            }
        });

        removeCommitteeButton.setText("-");
        removeCommitteeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeCommitteeButtonActionPerformed(evt);
            }
        });

        committeePanelHolder.setBackground(java.awt.SystemColor.activeCaption);
        committeePanelHolder.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(committeeListLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(committeeListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addCommitteeButton)
                                .addGap(9, 9, 9)
                                .addComponent(removeCommitteeButton)))
                        .addGap(20, 20, 20)
                        .addComponent(committeePanelHolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(committeeListLabel)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(committeeListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addCommitteeButton)
                            .addComponent(removeCommitteeButton)))
                    .addComponent(committeePanelHolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void committeeListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_committeeListValueChanged
        // TODO add your handling code here:
        if(committeeList.getSelectedIndex() >= 0){
            Committee c = manager.getEventManager().getSelectedEvent().getCommitteeList().get(committeeList.getSelectedIndex());
            manager.getCommitteeManager().setSelectedCommittee(c);
            committeePanel.updateInfo();
        }
    }//GEN-LAST:event_committeeListValueChanged

    private void addCommitteeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCommitteeButtonActionPerformed
        // TODO add your handling code here:
        NewCommitteeDialog cd = new NewCommitteeDialog((JFrame)SwingUtilities.windowForComponent(this), true);
        cd.setVisible(true);
        if(cd.getConfirm()){
            try
            {
                manager.getCommitteeManager().setSelectedCommittee(manager.getEventManager().createCommittee(cd.createCommittee(),manager.getLogInManager().getLoggedInUser()));
                committeeList.setSelectedIndex(manager.getEventManager().getSelectedEvent().getCommitteeList().size()-1);
                committeePanel.setVisible(true);
            }
            catch (Exception e) {
                e.printStackTrace();
            }
            updateInfo();
            
        }
    }//GEN-LAST:event_addCommitteeButtonActionPerformed

    private void removeCommitteeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeCommitteeButtonActionPerformed
        // TODO add your handling code here:
        Committee c = manager.getEventManager().getSelectedEvent().getCommitteeList().get(committeeList.getSelectedIndex());
        //System.out.println(c);
        try
        {
            manager.getEventManager().deleteCommittee(c, manager.getUserManager().getSelectedUser());
        }
        catch (Exception e)
        {
                System.out.println(e);
                e.printStackTrace();
        }
        updateInfo();
        if(committeeList.getModel().getSize() > 0)
        {
            committeeList.setSelectedIndex(0);
        }
        else
        {
            committeePanel.setVisible(false);
        }
    }//GEN-LAST:event_removeCommitteeButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCommitteeButton;
    private javax.swing.JList committeeList;
    private javax.swing.JLabel committeeListLabel;
    private javax.swing.JScrollPane committeeListScrollPane;
    private javax.swing.JPanel committeePanelHolder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel noPanel;
    private javax.swing.JButton removeCommitteeButton;
    // End of variables declaration//GEN-END:variables
}
