/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import GUI.Dialog.NewCommitteeDialog;
import javax.swing.*;
import BackEnd.ManagerSystem.EventManager;
import BackEnd.EventSystem.Committee;
import BackEnd.ManagerSystem.MainManager;
import BackEnd.UserSystem.User;
/**
 *
 * @author Sid
 */
public class CommitteeListPanel extends javax.swing.JPanel {

    /**
     * Creates new form CommitteeListPanel
     */
    MainManager manager;
    public CommitteeListPanel() {
        initComponents();
        manager = MainManager.getInstance();
        updateInfo();
    }
    
    public void updateInfo()
    {
        DefaultListModel model = new DefaultListModel();
        model.clear();
        for(Committee c : manager.getEventManager().getSelectedEvent().getCommitteeList()){
            model.addElement(c.getTitle());
        }
        committeeList.setModel(model);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sortByGroup = new javax.swing.ButtonGroup();
        committeeListScrollPane = new javax.swing.JScrollPane();
        committeeList = new javax.swing.JList();
        searchLabel = new javax.swing.JLabel();
        searchTextField = new javax.swing.JTextField();
        searchValueComboBox = new javax.swing.JComboBox();
        taskProgressHighRadio = new javax.swing.JRadioButton();
        taskProgressLowRadio = new javax.swing.JRadioButton();
        expensesHighRadio = new javax.swing.JRadioButton();
        expensesLowRadio = new javax.swing.JRadioButton();
        incomeHighRadio = new javax.swing.JRadioButton();
        incomeLowRadio = new javax.swing.JRadioButton();
        sortByLabel = new javax.swing.JLabel();
        numMembersRadio = new javax.swing.JRadioButton();
        totalTasksRadio = new javax.swing.JRadioButton();
        committeeListLabel = new javax.swing.JLabel();
        searchButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        committeePanel1 = new GUI.CommitteePanel();
        addCommitteeButton = new javax.swing.JButton();
        removeCommitteeButton = new javax.swing.JButton();
        nameRadio = new javax.swing.JRadioButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        committeeList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        committeeList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                committeeListValueChanged(evt);
            }
        });
        committeeListScrollPane.setViewportView(committeeList);

        add(committeeListScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 116, 294));

        searchLabel.setText("Find by Value:");
        add(searchLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 271, -1, -1));

        searchTextField.setText("search term...");
        searchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTextFieldActionPerformed(evt);
            }
        });
        add(searchTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 268, 100, -1));

        searchValueComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Committee Name", "Chairperson Name", "Member Name", "etc..." }));
        searchValueComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchValueComboBoxActionPerformed(evt);
            }
        });
        add(searchValueComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 294, 172, -1));

        sortByGroup.add(taskProgressHighRadio);
        taskProgressHighRadio.setText("Task Progress(High)");
        taskProgressHighRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taskProgressHighRadioActionPerformed(evt);
            }
        });
        add(taskProgressHighRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 58, -1, -1));

        sortByGroup.add(taskProgressLowRadio);
        taskProgressLowRadio.setText("Task Progress(Low)");
        add(taskProgressLowRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 81, -1, -1));

        sortByGroup.add(expensesHighRadio);
        expensesHighRadio.setText("Expenses(High)");
        expensesHighRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expensesHighRadioActionPerformed(evt);
            }
        });
        add(expensesHighRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 127, -1, -1));

        sortByGroup.add(expensesLowRadio);
        expensesLowRadio.setText("Expenses(Low)");
        add(expensesLowRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 150, -1, -1));

        sortByGroup.add(incomeHighRadio);
        incomeHighRadio.setText("Income(High)");
        add(incomeHighRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 173, -1, -1));

        sortByGroup.add(incomeLowRadio);
        incomeLowRadio.setText("Income(Low)");
        add(incomeLowRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 196, -1, -1));

        sortByLabel.setText("Sort By....");
        add(sortByLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 0, -1, -1));

        sortByGroup.add(numMembersRadio);
        numMembersRadio.setText("# of members");
        add(numMembersRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 219, -1, -1));

        sortByGroup.add(totalTasksRadio);
        totalTasksRadio.setText("Total Tasks");
        totalTasksRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalTasksRadioActionPerformed(evt);
            }
        });
        add(totalTasksRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 104, -1, -1));

        committeeListLabel.setText("Committee List");
        add(committeeListLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 320, -1, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 0, 10, 448));
        add(committeePanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 11, -1, -1));

        addCommitteeButton.setText("+");
        addCommitteeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCommitteeButtonActionPerformed(evt);
            }
        });
        add(addCommitteeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        removeCommitteeButton.setText("-");
        removeCommitteeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeCommitteeButtonActionPerformed(evt);
            }
        });
        add(removeCommitteeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 320, -1, -1));

        sortByGroup.add(nameRadio);
        nameRadio.setText("Name");
        add(nameRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 35, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void searchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTextFieldActionPerformed

    private void searchValueComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchValueComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchValueComboBoxActionPerformed

    private void taskProgressHighRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taskProgressHighRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taskProgressHighRadioActionPerformed

    private void expensesHighRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expensesHighRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expensesHighRadioActionPerformed

    private void totalTasksRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalTasksRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalTasksRadioActionPerformed

    private void committeeListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_committeeListValueChanged
        // TODO add your handling code here:
        if(committeeList.getSelectedIndex() >= 0){
            Committee c = manager.getEventManager().getSelectedEvent().getCommitteeList().get(committeeList.getSelectedIndex());
            committeePanel1.setCommittee(c);
        }
    }//GEN-LAST:event_committeeListValueChanged

    private void addCommitteeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCommitteeButtonActionPerformed
        // TODO add your handling code here:
        NewCommitteeDialog cd = new NewCommitteeDialog((JFrame)SwingUtilities.windowForComponent(this), true);
        cd.setVisible(true);
        if(cd.getConfirm()){
            try{
            manager.getEventManager().addCommittee(cd.createCommittee(),manager.getUserManager().getSelectedUser());
            }
            catch (Exception e) {
                e.printStackTrace();
            }
            updateInfo();
        }
    }//GEN-LAST:event_addCommitteeButtonActionPerformed

    private void removeCommitteeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeCommitteeButtonActionPerformed
        // TODO add your handling code here:
        Committee c = manager.getEventManager().getSelectedEvent().getCommitteeList().get(committeeList.getSelectedIndex());
        System.out.println(c);
        try
        {
            manager.getEventManager().removeCommittee(c, manager.getUserManager().getSelectedUser());
        }
        catch (Exception e)
        {
                System.out.println(e);
                e.printStackTrace();
        }
        updateInfo();
    }//GEN-LAST:event_removeCommitteeButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Not implemented yet.");
    }//GEN-LAST:event_searchButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCommitteeButton;
    private javax.swing.JList committeeList;
    private javax.swing.JLabel committeeListLabel;
    private javax.swing.JScrollPane committeeListScrollPane;
    private GUI.CommitteePanel committeePanel1;
    private javax.swing.JRadioButton expensesHighRadio;
    private javax.swing.JRadioButton expensesLowRadio;
    private javax.swing.JRadioButton incomeHighRadio;
    private javax.swing.JRadioButton incomeLowRadio;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton nameRadio;
    private javax.swing.JRadioButton numMembersRadio;
    private javax.swing.JButton removeCommitteeButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JComboBox searchValueComboBox;
    private javax.swing.ButtonGroup sortByGroup;
    private javax.swing.JLabel sortByLabel;
    private javax.swing.JRadioButton taskProgressHighRadio;
    private javax.swing.JRadioButton taskProgressLowRadio;
    private javax.swing.JRadioButton totalTasksRadio;
    // End of variables declaration//GEN-END:variables
}
