/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BackEnd.EventSystem.Committee;
import BackEnd.EventSystem.Expense;
import BackEnd.ManagerSystem.MainManager;
import GUI.Dialog.NewExpenseDialog;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sara
 */
public class Expenses extends javax.swing.JPanel {

    /**
     * Creates new form Expenses
     */
    private MainManager manager;
    public Expenses() {
        initComponents();
        manager = MainManager.getInstance();
        updateInfo();
    }
    
    public void updateInfo()
    {
        DefaultTableModel model = getTableModel();
        model.setRowCount(0);
        if(manager.getCommitteeManager().getSelectedCommittee() != null)
        {
            Committee c = manager.getCommitteeManager().getSelectedCommittee();
            for(Expense e : c.getBudget().getExpenseList())
            {
                model.addRow(
                    new Object[]
                    {
                        e.getBUDGET_ITEM_ID(),e.getDescription(),e.getValue()
                    });
            }
        }
        
    }
    
    public DefaultTableModel getTableModel()
    { return (DefaultTableModel)expensesTable.getModel(); }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        expensesLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        expensesTable = new javax.swing.JTable();
        addExpenseButton = new javax.swing.JButton();
        deleteExpenseButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(325, 500));

        expensesLabel.setFont(new java.awt.Font("Candara", 1, 16)); // NOI18N
        expensesLabel.setText("Expenses");

        jScrollPane1.setPreferredSize(new java.awt.Dimension(300, 500));

        expensesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Description", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        expensesTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(expensesTable);
        expensesTable.getColumnModel().getColumn(0).setResizable(false);
        expensesTable.getColumnModel().getColumn(0).setPreferredWidth(100);
        expensesTable.getColumnModel().getColumn(1).setResizable(false);
        expensesTable.getColumnModel().getColumn(1).setPreferredWidth(300);
        expensesTable.getColumnModel().getColumn(2).setResizable(false);
        expensesTable.getColumnModel().getColumn(2).setPreferredWidth(100);

        addExpenseButton.setText("Add Expense");
        addExpenseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addExpenseButtonActionPerformed(evt);
            }
        });

        deleteExpenseButton.setText("Delete Expense");
        deleteExpenseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteExpenseButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(addExpenseButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(deleteExpenseButton))
                    .add(layout.createSequentialGroup()
                        .add(expensesLabel)
                        .add(0, 0, Short.MAX_VALUE))
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(expensesLabel)
                .add(18, 18, 18)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(deleteExpenseButton)
                    .add(addExpenseButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addExpenseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addExpenseButtonActionPerformed
        NewExpenseDialog ned = new NewExpenseDialog(null, true);
        ned.setVisible(true);
        if(ned.getConfirm())
        {
            try
            {
                Expense e = ned.createExpense();
                manager.getBudgetManager().createExpense(e, manager.getLogInManager().getLoggedInUser(), manager.getEventManager().getSelectedEvent(), manager.getCommitteeManager().getSelectedCommittee());
            }
            catch (Exception e)
            {
                e.printStackTrace();
            }
        }
        updateInfo();
    }//GEN-LAST:event_addExpenseButtonActionPerformed

    private void deleteExpenseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteExpenseButtonActionPerformed
        int selection = expensesTable.getSelectedRow();
        Expense expense = manager.getCommitteeManager().getSelectedCommittee().getBudget().getExpenseList().get(selection);
        try
        {
            manager.getBudgetManager().deleteExpense(expense, manager.getLogInManager().getLoggedInUser(), manager.getEventManager().getSelectedEvent(), manager.getCommitteeManager().getSelectedCommittee());
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        updateInfo();
    }//GEN-LAST:event_deleteExpenseButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addExpenseButton;
    private javax.swing.JButton deleteExpenseButton;
    private javax.swing.JLabel expensesLabel;
    private javax.swing.JTable expensesTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
