/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BackEnd.EventSystem.Committee;
import BackEnd.ManagerSystem.EventManager;
import BackEnd.ManagerSystem.MainManager;
import BackEnd.ManagerSystem.PrivilegeInsufficientException;
import GUI.Reportable.EventDialog;
import java.awt.CardLayout;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;

/**
 *
 * @author sara
 */
public class Main extends javax.swing.JPanel {

    
    private MainManager manager;
    private UserManagementPanel ump;
    private MainPanel mainPanel;
    private DesignDefault dd;
    /**
     * Creates new form Main
     */
    public Main() throws PrivilegeInsufficientException {
        dd = DesignDefault.getInstance();
        initComponents();
        mainPanel = new MainPanel();
        BudgetPanel bp = new BudgetPanel();
        ump = new UserManagementPanel();
        CommitteeListPanel clp = new CommitteeListPanel();
        EmailPanel ep = new EmailPanel();
        SwitchingPanelHolder.add(mainPanel, "home");
        SwitchingPanelHolder.add(clp, "committees");
        SwitchingPanelHolder.add(ep, "email");
        SwitchingPanelHolder.add(bp, "budget");
        SwitchingPanelHolder.add(ump, "userManagement");
        manager = MainManager.getInstance();
        this.setSize(dd.getFrameDimension());
        this.setBackground(dd.getBGColor());
        updateInfo();
    }
    
    public void updateInfo()
    {
        
        DefaultComboBoxModel listModel = new DefaultComboBoxModel();
        listModel.removeAllElements();
        for(Committee c : manager.getEventManager().getSelectedEvent().getCommitteeList()){
            listModel.addElement(c.getTitle());
        }
        //committeesComboBox.setModel(listModel);
        
    }
    
    public UserManagementPanel getUserManagementPanel()
    {
        return ump;
    }

    public void setParticipantView() {
        mainPanel.setParticipantView();
        ump.setNonAdminView();
        budgetPanel.setVisible(false);
        committeesPanel.setVisible(false);
        reportsPanel.setVisible(false);
        tasksPanel.setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tasksPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        committeesPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        changeCommitteesButton = new javax.swing.JButton();
        participantsPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        changeUserManagementButton = new javax.swing.JButton();
        reportsPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        budgetPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        changeBudgetButton = new javax.swing.JButton();
        emailPanel = new javax.swing.JPanel();
        changeEmailButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        SwitchingPanelHolder = new javax.swing.JPanel();
        ChangeHomeButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(160, 160, 160));
        setMaximumSize(new java.awt.Dimension(960, 680));
        setMinimumSize(new java.awt.Dimension(960, 680));
        setPreferredSize(new java.awt.Dimension(960, 680));

        tasksPanel.setBackground(dd.getPanelBGColor());
        tasksPanel.setMaximumSize(new java.awt.Dimension(160, 80));
        tasksPanel.setMinimumSize(new java.awt.Dimension(160, 80));
        tasksPanel.setPreferredSize(new java.awt.Dimension(160, 80));

        jLabel5.setFont(dd.getStandardText());
        jLabel5.setText("Tasks Progress");

        org.jdesktop.layout.GroupLayout tasksPanelLayout = new org.jdesktop.layout.GroupLayout(tasksPanel);
        tasksPanel.setLayout(tasksPanelLayout);
        tasksPanelLayout.setHorizontalGroup(
            tasksPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(tasksPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(tasksPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(tasksPanelLayout.createSequentialGroup()
                        .add(jLabel5)
                        .add(0, 68, Short.MAX_VALUE))
                    .add(jProgressBar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        tasksPanelLayout.setVerticalGroup(
            tasksPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(tasksPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel5)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jProgressBar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        committeesPanel.setBackground(dd.getPanelBGColor());
        committeesPanel.setMaximumSize(new java.awt.Dimension(160, 80));
        committeesPanel.setMinimumSize(new java.awt.Dimension(160, 80));
        committeesPanel.setPreferredSize(new java.awt.Dimension(160, 80));

        jLabel6.setFont(dd.getStandardText());
        jLabel6.setText("Committees");

        changeCommitteesButton.setFont(dd.getStandardText());
        changeCommitteesButton.setMinimumSize(dd.getBigButtonDimension());
        changeCommitteesButton.setText("Manage");
        changeCommitteesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeCommitteesButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout committeesPanelLayout = new org.jdesktop.layout.GroupLayout(committeesPanel);
        committeesPanel.setLayout(committeesPanelLayout);
        committeesPanelLayout.setHorizontalGroup(
            committeesPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, committeesPanelLayout.createSequentialGroup()
                .add(0, 0, Short.MAX_VALUE)
                .add(changeCommitteesButton))
            .add(committeesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel6)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        committeesPanelLayout.setVerticalGroup(
            committeesPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(committeesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel6)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 32, Short.MAX_VALUE)
                .add(changeCommitteesButton))
        );

        participantsPanel.setBackground(dd.getPanelBGColor());
        participantsPanel.setMaximumSize(new java.awt.Dimension(160, 80));
        participantsPanel.setMinimumSize(new java.awt.Dimension(160, 80));
        participantsPanel.setPreferredSize(new java.awt.Dimension(160, 80));

        jLabel7.setFont(dd.getStandardText());
        jLabel7.setText("Participants");

        changeUserManagementButton.setFont(dd.getStandardText());
        changeUserManagementButton.setMinimumSize(dd.getBigButtonDimension());
        changeUserManagementButton.setText("Manage");
        changeUserManagementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeUserManagementButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout participantsPanelLayout = new org.jdesktop.layout.GroupLayout(participantsPanel);
        participantsPanel.setLayout(participantsPanelLayout);
        participantsPanelLayout.setHorizontalGroup(
            participantsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(participantsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel7)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, participantsPanelLayout.createSequentialGroup()
                .add(0, 0, Short.MAX_VALUE)
                .add(changeUserManagementButton))
        );
        participantsPanelLayout.setVerticalGroup(
            participantsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(participantsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel7)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 32, Short.MAX_VALUE)
                .add(changeUserManagementButton))
        );

        reportsPanel.setBackground(dd.getPanelBGColor());
        reportsPanel.setMaximumSize(new java.awt.Dimension(160, 80));
        reportsPanel.setMinimumSize(new java.awt.Dimension(160, 80));
        reportsPanel.setPreferredSize(new java.awt.Dimension(160, 80));

        jLabel4.setFont(dd.getStandardText());
        jLabel4.setText("Reports");

        jButton6.setFont(dd.getStandardText());
        jButton6.setText("View");
        jButton6.setMinimumSize(dd.getBigButtonDimension());
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout reportsPanelLayout = new org.jdesktop.layout.GroupLayout(reportsPanel);
        reportsPanel.setLayout(reportsPanelLayout);
        reportsPanelLayout.setHorizontalGroup(
            reportsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(reportsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel4)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, reportsPanelLayout.createSequentialGroup()
                .add(0, 0, Short.MAX_VALUE)
                .add(jButton6))
        );
        reportsPanelLayout.setVerticalGroup(
            reportsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(reportsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel4)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 32, Short.MAX_VALUE)
                .add(jButton6))
        );

        budgetPanel.setBackground(dd.getPanelBGColor());
        budgetPanel.setMaximumSize(new java.awt.Dimension(160, 160));
        budgetPanel.setMinimumSize(new java.awt.Dimension(160, 160));
        budgetPanel.setPreferredSize(new java.awt.Dimension(160, 160));

        jLabel1.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel1.setText("Budget");

        jLabel2.setText("Income:");

        jLabel3.setText("Expenses:");

        changeBudgetButton.setFont(dd.getStandardText());
        changeBudgetButton.setText("Details");
        changeBudgetButton.setMinimumSize(dd.getBigButtonDimension());
        changeBudgetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeBudgetButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout budgetPanelLayout = new org.jdesktop.layout.GroupLayout(budgetPanel);
        budgetPanel.setLayout(budgetPanelLayout);
        budgetPanelLayout.setHorizontalGroup(
            budgetPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(budgetPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(budgetPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1)
                    .add(jLabel2)
                    .add(jLabel3))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, budgetPanelLayout.createSequentialGroup()
                .add(0, 0, Short.MAX_VALUE)
                .add(changeBudgetButton))
        );
        budgetPanelLayout.setVerticalGroup(
            budgetPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(budgetPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 68, Short.MAX_VALUE)
                .add(changeBudgetButton))
        );

        emailPanel.setBackground(dd.getPanelBGColor());
        emailPanel.setMaximumSize(new java.awt.Dimension(160, 80));
        emailPanel.setMinimumSize(new java.awt.Dimension(160, 80));
        emailPanel.setPreferredSize(new java.awt.Dimension(160, 80));

        changeEmailButton.setFont(dd.getStandardText());
        changeEmailButton.setText("Email");
        changeEmailButton.setMinimumSize(dd.getBigButtonDimension());
        changeEmailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeEmailButtonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel8.setText("Contact");

        org.jdesktop.layout.GroupLayout emailPanelLayout = new org.jdesktop.layout.GroupLayout(emailPanel);
        emailPanel.setLayout(emailPanelLayout);
        emailPanelLayout.setHorizontalGroup(
            emailPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, emailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel8)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, emailPanelLayout.createSequentialGroup()
                .add(0, 0, Short.MAX_VALUE)
                .add(changeEmailButton))
        );
        emailPanelLayout.setVerticalGroup(
            emailPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(emailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel8)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 28, Short.MAX_VALUE)
                .add(changeEmailButton))
        );

        jLabel11.setFont(new java.awt.Font("Candara", 1, 16)); // NOI18N
        jLabel11.setText("Manage Event");

        SwitchingPanelHolder.setMaximumSize(new java.awt.Dimension(760, 620));
        SwitchingPanelHolder.setMinimumSize(new java.awt.Dimension(760, 620));
        SwitchingPanelHolder.setPreferredSize(new java.awt.Dimension(760, 620));
        SwitchingPanelHolder.setLayout(new java.awt.CardLayout());

        ChangeHomeButton.setText("Home");
        ChangeHomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeHomeButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel11)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 615, Short.MAX_VALUE)
                        .add(ChangeHomeButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(SwitchingPanelHolder, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 20, Short.MAX_VALUE)))
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, tasksPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, committeesPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, participantsPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, emailPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, reportsPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(budgetPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(tasksPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(committeesPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(participantsPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(reportsPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(budgetPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(emailPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(ChangeHomeButton))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(SwitchingPanelHolder, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 620, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void changeEmailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeEmailButtonActionPerformed
        CardLayout cl = (CardLayout)(SwitchingPanelHolder.getLayout());
        cl.show(SwitchingPanelHolder, "email");
    }//GEN-LAST:event_changeEmailButtonActionPerformed

    private void changeBudgetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeBudgetButtonActionPerformed
        CardLayout cl = (CardLayout)(SwitchingPanelHolder.getLayout());
        cl.show(SwitchingPanelHolder, "budget");
    }//GEN-LAST:event_changeBudgetButtonActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        EventDialog ed = new EventDialog(null, true);
        ed.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void changeCommitteesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeCommitteesButtonActionPerformed
        CardLayout cl = (CardLayout)(SwitchingPanelHolder.getLayout());
        cl.show(SwitchingPanelHolder, "committees");
    }//GEN-LAST:event_changeCommitteesButtonActionPerformed

    private void ChangeHomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeHomeButtonActionPerformed
        CardLayout cl = (CardLayout)(SwitchingPanelHolder.getLayout());
        cl.show(SwitchingPanelHolder, "home");
    }//GEN-LAST:event_ChangeHomeButtonActionPerformed

    private void changeUserManagementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeUserManagementButtonActionPerformed
        CardLayout cl = (CardLayout)(SwitchingPanelHolder.getLayout());
        cl.show(SwitchingPanelHolder, "userManagement");
    }//GEN-LAST:event_changeUserManagementButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChangeHomeButton;
    private javax.swing.JPanel SwitchingPanelHolder;
    private javax.swing.JPanel budgetPanel;
    private javax.swing.JButton changeBudgetButton;
    private javax.swing.JButton changeCommitteesButton;
    private javax.swing.JButton changeEmailButton;
    private javax.swing.JButton changeUserManagementButton;
    private javax.swing.JPanel committeesPanel;
    private javax.swing.JPanel emailPanel;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JPanel participantsPanel;
    private javax.swing.JPanel reportsPanel;
    private javax.swing.JPanel tasksPanel;
    // End of variables declaration//GEN-END:variables
}
