/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author Karina
 */
public class MainPanel extends javax.swing.JPanel {

    JPanel calendarSelectionPanel;
    JButton selectCalendarButton, selectEventDetailsButton;
    JPanel calendarSwitchingPanel;
    /**
     * Creates new form MainPanel
     */
    public MainPanel() {
        initComponents();
        setLayout(new BorderLayout());
        calendarSelectionPanel = new JPanel();
        calendarSwitchingPanel = new JPanel();
        
        selectCalendarButton = new JButton("Calendar");
        selectEventDetailsButton = new JButton("Event Details");
        selectCalendarButton.addActionListener(new CalendarButtonListener());
        selectEventDetailsButton.addActionListener(new CalendarButtonListener());
        
        calendarSwitchingPanel.setLayout(new CardLayout());
        calendarSelectionPanel.add(selectCalendarButton);
        calendarSelectionPanel.add(selectEventDetailsButton);
        CalendarPanel cp = new CalendarPanel();
        EventDetailsPanel edp = new EventDetailsPanel();
       calendarSwitchingPanel.add(cp, "calendar");
       calendarSwitchingPanel.add(edp, "eventDetails");
       add(calendarSwitchingPanel, BorderLayout.NORTH);
       add(calendarSelectionPanel, BorderLayout.SOUTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    private void selectCalendarButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        CardLayout cl = (CardLayout)(calendarSwitchingPanel.getLayout());
        System.out.println("HELLO");
        cl.show(calendarSwitchingPanel, "calendar");
    } 
    
    private void selectEventDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        CardLayout cl = (CardLayout)(calendarSwitchingPanel.getLayout());
        System.out.println("HELLOL");
        cl.show(calendarSwitchingPanel, "eventDetails");
    } 

    private class CalendarButtonListener implements ActionListener {

        public void actionPerformed(ActionEvent e) {
            if (e.getSource() == selectCalendarButton)
                selectCalendarButtonActionPerformed(e);
            if (e.getSource() == selectEventDetailsButton)
                selectEventDetailsButtonActionPerformed(e);
        }
    }
}
