/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import GUI.Reportable.BudgetReport;

/**
 *
 * @author sara
 */
public class TotalBudgetPanel extends javax.swing.JPanel {

    /**
     * Creates new form TotalBudgetPanel
     */
    private TotalBudgetIncome budgetIncome;
    private TotalBudgetExpense budgetExpense;
    
    public TotalBudgetPanel() {
        initComponents();
        
        budgetIncome = new TotalBudgetIncome();
        budgetExpense = new TotalBudgetExpense();
        
        incomePanel.add(budgetIncome);
        expensePanel.add(budgetExpense);
                
        incomePanel.setVisible(true);
        expensePanel.setVisible(true);
    }
    
    public void updateInfo(){
        budgetIncome.updateInfo();
        budgetExpense.updateInfo();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        budgetLabel = new javax.swing.JLabel();
        reportButton = new javax.swing.JButton();
        incomePanel = new javax.swing.JPanel();
        expensePanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(760, 620));

        budgetLabel.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        budgetLabel.setText("Total Budget");
        budgetLabel.setBounds(new java.awt.Rectangle(2, 2, 2, 2));

        reportButton.setText("Report");
        reportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportButtonActionPerformed(evt);
            }
        });

        incomePanel.setBackground(new java.awt.Color(255, 255, 255));
        incomePanel.setPreferredSize(new java.awt.Dimension(370, 600));

        expensePanel.setBackground(new java.awt.Color(255, 255, 255));
        expensePanel.setPreferredSize(new java.awt.Dimension(370, 580));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(incomePanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(expensePanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
            .add(layout.createSequentialGroup()
                .add(budgetLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(reportButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(budgetLabel)
                    .add(reportButton))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(expensePanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
                    .add(incomePanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void reportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportButtonActionPerformed
        BudgetReport budgetReport = new BudgetReport(null,true);
        budgetReport.setVisible(true);
    }//GEN-LAST:event_reportButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel budgetLabel;
    private javax.swing.JPanel expensePanel;
    private javax.swing.JPanel incomePanel;
    private javax.swing.JButton reportButton;
    // End of variables declaration//GEN-END:variables
}
