/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Dialog;

import BackEnd.EventSystem.SubEvent;
import BackEnd.EventSystem.TimeSchedule;
import BackEnd.ManagerSystem.MainManager;
import BackEnd.ManagerSystem.PrivilegeInsufficientException;
import BackEnd.UserSystem.Location;
import EMS_Database.DoesNotExistException;
import GUI.SubEventPanel;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Karina
 */
public class EditSubEventDialog extends javax.swing.JDialog {

    private boolean confirm;
    private SubEvent selectedSubEvent;
    private MainManager manager;
    private SubEventPanel sep = new SubEventPanel();
    /**
     * Creates new form EditSubEventDialog
     */
    public EditSubEventDialog(java.awt.Frame parent, SubEvent se, boolean modal) {
        super(parent, modal);
        selectedSubEvent = se;
        initComponents();
        nameField.setText(selectedSubEvent.getDescription());
        manager = MainManager.getInstance();
        confirm = false;
        
        DefaultComboBoxModel dayModel = new DefaultComboBoxModel();
        for(int i = 0; i < 32; i++)
        {
            if(i == 0)
            { dayModel.addElement("Day"); }
            else
            { dayModel.addElement(i); }
        }
        DefaultComboBoxModel yearModel = new DefaultComboBoxModel();
        yearModel.addElement("Year");
        for(int i = 2013; i < 2050; i++)
        {
            yearModel.addElement(i);
        }
        DefaultComboBoxModel minModel = new DefaultComboBoxModel();
        minModel.addElement("Minute");
        for(int i = 1; i < 61; i++)
        {
            minModel.addElement(i);
        }
        daySelect.setModel((ComboBoxModel)dayModel);
        yearSelect.setModel((ComboBoxModel)yearModel);
        minuteSelect.setModel(minModel);
        
    }
    
    public boolean getConfirm()
    { return confirm; }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        saveSubEventButton = new javax.swing.JButton();
        cancelChangesButton = new javax.swing.JButton();
        monthSelect = new javax.swing.JComboBox();
        monthDayYearLabel = new javax.swing.JLabel();
        daySelect = new javax.swing.JComboBox();
        yearSelect = new javax.swing.JComboBox();
        locationField = new javax.swing.JTextField();
        minuteSelect = new javax.swing.JComboBox();
        durationField = new javax.swing.JTextField();
        durationLabel = new javax.swing.JLabel();
        locationLabel = new javax.swing.JLabel();
        pmCheck = new javax.swing.JCheckBox();
        startLabel = new javax.swing.JLabel();
        hourSelect = new javax.swing.JComboBox();
        headerLabel = new javax.swing.JLabel();
        descriptionScrollPane = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();
        nameField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        saveSubEventButton.setText("Save Sub Event");
        saveSubEventButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveSubEventButtonActionPerformed(evt);
            }
        });

        cancelChangesButton.setText("Cancel Changes");
        cancelChangesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelChangesButtonActionPerformed(evt);
            }
        });

        monthSelect.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Month", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        monthDayYearLabel.setText("Month/Day/Year");

        daySelect.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Day" }));

        yearSelect.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Year" }));

        minuteSelect.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Minute" }));

        durationField.setText("00:00");
        durationField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                durationFieldActionPerformed(evt);
            }
        });

        durationLabel.setText("Duration:");

        locationLabel.setText("Location:");

        pmCheck.setText("PM");
        pmCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pmCheckActionPerformed(evt);
            }
        });

        startLabel.setText("Start Time:");

        hourSelect.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hour", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        headerLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        headerLabel.setText("SubEvent Name");

        descriptionTextArea.setColumns(20);
        descriptionTextArea.setRows(5);
        descriptionTextArea.setText("Description of this event.\nDoesn't do anything yet.");
        descriptionScrollPane.setViewportView(descriptionTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(monthDayYearLabel)
                                    .addComponent(startLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(monthSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(daySelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(yearSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(durationField, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(locationField, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(hourSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(minuteSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(pmCheck))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(durationLabel)
                                    .addComponent(locationLabel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(saveSubEventButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cancelChangesButton)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(88, 88, 88))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descriptionScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(headerLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nameField)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(headerLabel)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(descriptionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(monthSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monthDayYearLabel)
                    .addComponent(daySelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startLabel)
                    .addComponent(pmCheck)
                    .addComponent(hourSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minuteSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(durationLabel)
                    .addComponent(durationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locationLabel)
                    .addComponent(locationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveSubEventButton)
                    .addComponent(cancelChangesButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void durationFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_durationFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_durationFieldActionPerformed

    private void pmCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pmCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pmCheckActionPerformed

    private void cancelChangesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelChangesButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelChangesButtonActionPerformed

    private void saveSubEventButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveSubEventButtonActionPerformed
        try {
            int year = yearSelect.getSelectedIndex() + 2012;
            int month = monthSelect.getSelectedIndex();
            int day = daySelect.getSelectedIndex();
            int hour = hourSelect.getSelectedIndex();
            if(pmCheck.isSelected())
            {
                hour += 12;
            }
            int min = minuteSelect.getSelectedIndex();
            TimeSchedule t = new TimeSchedule();
            t.setStartDateTime(year, month, day, hour, min);
            selectedSubEvent.setTimeSchedule(t);
            selectedSubEvent.setLocation(new Location(locationField.getText()));
            selectedSubEvent.setDescription(nameField.getText());
            
            manager.getEventManager().createSubEvent(selectedSubEvent, manager.getLogInManager().getLoggedInUser());
        } catch (PrivilegeInsufficientException ex) {
            Logger.getLogger(EditSubEventDialog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DoesNotExistException ex) {
            Logger.getLogger(EditSubEventDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saveSubEventButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelChangesButton;
    private javax.swing.JComboBox daySelect;
    private javax.swing.JScrollPane descriptionScrollPane;
    private javax.swing.JTextArea descriptionTextArea;
    private javax.swing.JTextField durationField;
    private javax.swing.JLabel durationLabel;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JComboBox hourSelect;
    private javax.swing.JTextField locationField;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JComboBox minuteSelect;
    private javax.swing.JLabel monthDayYearLabel;
    private javax.swing.JComboBox monthSelect;
    private javax.swing.JTextField nameField;
    private javax.swing.JCheckBox pmCheck;
    private javax.swing.JButton saveSubEventButton;
    private javax.swing.JLabel startLabel;
    private javax.swing.JComboBox yearSelect;
    // End of variables declaration//GEN-END:variables
}
